### ISSUE TITLE
This is supposed to be a bot

### ISSUE THREAD

**Issue by foxcqrn** [MCPluginDev/FreedomBot#10]
As the name of this plugin says, this is a bot. There should be more stuff in the listener. I don't feel like more commands are needed, as we should have the listener automatically do things.

**Comment by foxcqrn** [comment]
This will hopefully be added in 3.0

**Comment by FoxIshDaBest** [comment]
@heroguy42 is doing this

**Comment by mayokek** [comment]
Superseded by #18
