### ISSUE TITLE
FreedomBot 3.0

### ISSUE THREAD

**Issue by foxcqrn** [MCPluginDev/FreedomBot#12]
FreedomBot has gone through many changes. My first idea of FreedomBot was to be a very small side project from working on FoxFreedom (later renamed to RainbowFreedom). Now, FoxFreedom/RainbowFreedom has been shut down and this became my main project.

FreedomBot 3.0 will introduce full support for 5.0, and lots of new changes. I am planning to add more to the listener soon.

Applications to become a FreedomBot developer might/might not be coming soon. If FB developers become inactive and don't contribute, I will open up applications.

**Comment by FoxIshDaBest** [comment]
Changed the default prefix to BLUEPREFIX, changed BOTPREFIX to REDPREFIX.

**Comment by DUFCLiam** [comment]
- Test [x ]

**Comment by DUFCLiam** [comment]
- [ ] Prefix
    - [ ] Change BLURPREFIX
    - [ ] Change BOTPREFIX to REDPREFIX

**Comment by foxcqrn** [comment]
Changed the default prefix to BLUEPREFIX; Changed BOTPREFIX to REDPREFIX

**Comment by mayokek** [comment]
Superseded by #18
