### ISSUE TITLE
FreedomBot Failed to compile.

### ISSUE THREAD

**Issue by foxcqrn** [MCPluginDev/FreedomBot#14]
ant -f "C:\Users\Rosseland Family\Documents\NetBeansProjects\FreedomBot3.0" -Dnb.internal.action.name=rebuild clean jar
init:
deps-clean:
Updating property file: C:\Users\Rosseland Family\Documents\NetBeansProjects\FreedomBot3.0\build\built-clean.properties
Deleting directory C:\Users\Rosseland Family\Documents\NetBeansProjects\FreedomBot3.0\build
clean:
init:
deps-jar:
Created dir: C:\Users\Rosseland Family\Documents\NetBeansProjects\FreedomBot3.0\build
Updating property file: C:\Users\Rosseland Family\Documents\NetBeansProjects\FreedomBot3.0\build\built-jar.properties
Created dir: C:\Users\Rosseland Family\Documents\NetBeansProjects\FreedomBot3.0\build\classes
Created dir: C:\Users\Rosseland Family\Documents\NetBeansProjects\FreedomBot3.0\build\empty
Created dir: C:\Users\Rosseland Family\Documents\NetBeansProjects\FreedomBot3.0\build\generated-sources\ap-source-output
Compiling 11 source files to C:\Users\Rosseland Family\Documents\NetBeansProjects\FreedomBot3.0\build\classes
C:\Users\Rosseland Family\Documents\NetBeansProjects\FreedomBot3.0\src\com\mcplugindev\freedombot\BotUtil.java:50: error: cannot access AbstractService
        TotalFreedom5_Getter.getInstance().getAdminList().addAdmin(new Admin(player));
  class file for net.pravian.aero.component.service.AbstractService not found
C:\Users\Rosseland Family\Documents\NetBeansProjects\FreedomBot3.0\src\com\mcplugindev\freedombot\TotalFreedom5_Getter.java:18: error: cannot access AeroPlugin
        freedommod = TotalFreedomMod.plugin();
  class file for net.pravian.aero.plugin.AeroPlugin not found
2 errors
C:\Users\Rosseland Family\Documents\NetBeansProjects\FreedomBot3.0\nbproject\build-impl.xml:948: The following error occurred while executing this line:
C:\Users\Rosseland Family\Documents\NetBeansProjects\FreedomBot3.0\nbproject\build-impl.xml:288: Compile failed; see the compiler error output for details.
BUILD FAILED (total time: 0 seconds)

**Comment by foxcqrn** [comment]
@AvalancheYT @DUFCLiam

**Comment by mayokek** [comment]
It's missing Aero plugin...

**Comment by foxcqrn** [comment]
LOL I'm a fucking idiot thanks @AvalancheYT
