### ISSUE TITLE
Config Update #2

### ISSUE THREAD

**Issue by foxcqrn** [MCPluginDev/FreedomBot#2]
@DUFCLiam,

Have you finished the config update yet? It has been a while now..

**Comment by DUFCLiam** [comment]
What shall be in configuration?

**Comment by mayokek** [comment]
I can takeover the config update...
We can always use custom YamlConfig for the plugin so we don't have to use different projects to use it as configuration.

**Comment by DUFCLiam** [comment]
@AvalancheYT I will let you take it over as I can't update it, Sorry.

**Comment by foxcqrn** [comment]
Alright thanks.

**Comment by foxcqrn** [comment]
Ill update the config I made when I get home.
