### ISSUE TITLE
FreedomBot 2.3-test Won't Load

### ISSUE THREAD

**Issue by foxcqrn** [MCPluginDev/FreedomBot#4]
@MCPluginDev/developers,

We have a problem. I have just now tested 2.3 but it isn't loading. I feel like its not working because I compiled it with TFM 4.3 and haven't updated everything to 5.0.

**Comment by mayokek** [comment]
I can fix that... If I fix that, do you want me to make compilable to TFM 5.0?

**Comment by foxcqrn** [comment]
I am working on making it compatible at the moment. Would you mind telling me the new way to add someone to the SA list?

**Comment by foxcqrn** [comment]
@AvalancheYT

**Comment by foxcqrn** [comment]
Nevermind. I guess I'll let you fix it. Make sure to update the 2.3 branch not master

**Comment by foxcqrn** [comment]
This has been fixed.
