### ISSUE TITLE
Commands and more stuff need / cleanup

### ISSUE THREAD

**Issue by ghost** [MCPluginDev/FreedomBot#5]
I want to add 2 admin commands
- Adminsupplys
- Cleanup
  And major config updates, I just wish to help out!

**Comment by foxcqrn** [comment]
Ill think about adding these. You might want to give more detail into explaining what these commands do.

**Comment by foxcqrn** [comment]
Added in v2.3pre-2

**Comment by foxcqrn** [comment]
This has been removed from the 3.0 release
